print("We are learning python!")
print("What a lovely day")
print()
print("Naah, I am too lazy to work, let's got to the pub!")
print("There", "are", "5", "apples", sep="-")
print("Python", "Java", "C++", sep=", ", end=" ")
print("and more!")
print("This is a line.\nAnd this is another line.")
print("Name:\tJohn")
print("Path to the folder: C:\\Users\\John")
print("Hello, what is your name?")
name = input()
print("Hello,", name, "it is nice to see you!")
name2 = input()
color = input()
print("Hello,", name, "this day seems very", color)
adress = input()
item = input()
cost = input()
print(item, cost, "deliver to:", adress)
statement = input()
print("Think about that and how it will help you")
# quiz: B,B,B,C,.py
team = input()
print(team, "is a champion!")
repeat = input()
print(repeat)
print("Enter a sentence to reverse the word order:")
sentence = input()  # Take the input sentence
reversed_sentence = " ".join(sentence.split()[::-1])  # Reverse the word order
print(reversed_sentence)  # Print the reversed sentence
